### ISSUE TITLE
404 errors with Num

### ISSUE THREAD

**Issue by etillier** [jidn/flask-obscure#1]
The obscure transformed value for Num returned by to_url can be greater than 4292967295, in which case the url will lead to a 404 error, given the max set for the IntegerConverter.__init__(self, map, max=4292967295). That max setting should probably be removed.

**Comment by jidn** [comment]
Do you have an example input value that causes this error?

**Comment by etillier** [comment]
salt=5498
original=9929
transformed=4293280982

**Comment by jidn** [comment]
The problem had already been fixed in [79fbcc](https://github.com/jidn/flask-obscure/commit/cf7c1a2d240bcad70f58d80660ee4da2cc79fbcc) but it appears I never repackaged it for pypi.  I have repackaged and tested with the file below.

```python
import flask
from flask_obscure import Obscure

app = flask.Flask(__name__)
app.config["OBSCURE_SALT"] = 5498
obscure = Obscure(app)


@app.route("/customer/<num:cust_id>", endpoint="get-cust")
def get(cust_id):
    # url='/customer/4293280982' expected cust_id=9929
    url = flask.url_for("get-cust", cust_id=cust_id)
    text = "\n".join(
        (
            f"Function received the unobscured cust_id={cust_id}",
            f"Creating url with the unobscured {url!r}",
        )
    )
    return flask.Response(text, content_type="text/plain")


if __name__ == "__main__":
    app.run()
```

**Comment by etillier** [comment]
Thanks!
